sudo: required
  
services:
  - docker

language: scala

scala:
  - 2.11.8

before_install:
  - docker run --rm -d -p "27017:27017" --name mongo mongo:3.2
script:
  - ./sbt test

after_success:
  - docker rm -f mongo

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# blacklist
branches:
  except:
    - RELEASE
